### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by jgradio64** [jgradio64/blog-style-social-media#1]
Create an Entity Relationship Diagram to determine the how we should design the database.
Use Draw.io and link page down below.

**Comment by jgradio64** [comment]
![entity_list](https://user-images.githubusercontent.com/47864214/197862281-190b7576-fa58-4156-90fe-5c79901bcfc0.jpg)
@wushileilei I attached the list of the entities for you to follow. If there is anything you need to add, feel free to do so, but add a comment here please.

**Comment by jgradio64** [comment]
Users can have many posts, comments and likes. 
A post belongs to one person but can have many comments and likes.
A comment belongs to one post, but can have many likes. 

I hope that helps.

**Comment by wushileilei** [comment]
[ClassProject.drawio.zip](https://github.com/jgradio64/blog-style-social-media/files/9872256/ClassProject.drawio.zip)
Use drawio to open this file. Git does not support .drawio so I made it a zip

**Comment by jgradio64** [comment]
ERD was good! I used it to complete the DB and hot it on Digital Ocean
